const keyboardENG = [
	'` 1 2 3 4 5 6 7 8 9 0 - = Backspace',
	'Tab q w e r t y u i o p [ ] \\ DEL',
	'CapsLock a s d f g h j k l ; \' ENTER',
	'Shift \\ z x c v b n m , . / up__key Shift',
	'Ctrl Win Alt Space Alt Ctrl left__key down__key right__key'];
const keyboardRU = {
	'`': 'ё',
	'': '',
	'=': '=',
	'-': '-',
	'1': '1',
	'2': '2',
	'3': '3',
	'4': '4',
	'5': '5',
	'6': '6',
	'7': '7',
	'8': '8',
	'9': '9',
	'0': '0',
	'q': 'й', 
	'w': 'ц', 
	'e': 'у',
	'r': 'к',
	't': 'е',
	'y': 'н',
	'u': 'г',
	'i': 'ш',
	'o': 'щ',
	'p': 'з',
	'[': 'х',
	']': 'ъ',
	'\\': '\\',
	'a': 'ф',
	's': 'ы',
	'd': 'в',
	'f': 'а',
	'g': 'п',
	'h': 'р',
	'j': 'о',
	'k': 'л',
	'l': 'д',
	';': 'ж',
	"'": 'э',
	'\\': '\\',
	'z': 'я',
	'x': 'ч',
	'c': 'с',
	'v': 'м',
	'b': 'и',
	'n': 'т',
	'm': 'ь',
	',': 'б',
	'.': 'ю',
	'/': '/',
	};
	const keyboardNum = ['~', '!', '@', '#', '$', '%', ':', '?', '*', '(', ')', '_', '+', 'Backspace'];
const funcKeysEvent = ['key space__key borders__key', 'key__num backspace__key borders__key key_100',
'del__key borders__key', 'up__key borders__key', 'left__key borders__key', 'right__key borders__key', 'down__key borders__key', 'enter__key borders__key', 'caps__key borders__key key_100', 'caps__key borders__key key_100 active', 'shift__left borders__key key_100', 'shift__left borders__key key_100 active', 'tab__key borders__key', 'alt__key alt__left borders__key', 'shift__right borders__key',
'shift__right borders__key active', 'alt__key alt__right borders__key', 'ctrl__key ctrl__left borders__key', 'ctrl__key ctrl__right borders__key', 'win__key borders__key'];
const keysEvent = ['key', 'key key__two','key key__one', 'key key__num', 'key key__num'];

export {funcKeysEvent, keysEvent, keyboardRU, keyboardENG, keyboardNum};